import { type RawVideo, type Category, CAT_WEIGHTS, BENCHMARKS } from '@/data/videos'
export type Stage = 'EMERGING'|'RISING'|'HOT'|'PEAK'|'SATURATED'|'DECLINING'
export type SortKey = 'opportunity'|'trend'|'velocity'|'freshness'
export interface Scores { reach:number;eng:number;vel:number;fresh:number;repro:number;sat:number;opp:number;trend:number;stage:Stage;insight:string }
export interface ScoredVideo extends RawVideo { scores:Scores }
export interface PercentileMaps { sorted:RawVideo[];vphSorted:RawVideo[] }
function clamp(v:number,lo=0,hi=100){return Math.min(hi,Math.max(lo,v))}
export function fmt(n:number):string{if(n>=1e6)return (n/1e6).toFixed(1)+'M';if(n>=1e3)return (n/1e3).toFixed(1)+'K';return String(n)}
export function buildPercentiles(videos:RawVideo[]):PercentileMaps{return{sorted:[...videos].sort((a,b)=>a.views-b.views),vphSorted:[...videos].sort((a,b)=>a.vphNow-b.vphNow)}}
function vp(v:RawVideo,s:RawVideo[]){const i=s.findIndex(x=>x.id===v.id);return(i/Math.max(s.length-1,1))*100}
function scoreReach(v:RawVideo,p:number){const b=v.views/Math.max(v.creator.followers,1);return clamp(0.4*p+0.6*(Math.log10(b+1)/Math.log10(101))*100)}
function scoreEngagement(v:RawVideo){const w=CAT_WEIGHTS[v.category as Category];const b=BENCHMARKS[v.category as Category];const k=v.views/1000;return clamp(w.saves*Math.min((v.saves/k)/b.saves,2)*50+w.shares*Math.min((v.shares/k)/b.shares,2)*50+w.comments*Math.min((v.comments/k)/b.comments,2)*50+w.likes*Math.min((v.likes/k)/b.likes,2)*50)}
function scoreVelocity(v:RawVideo,p:number){const m=v.ageHours<24?1.30:v.ageHours<48?1.15:v.ageHours<72?1.00:v.ageHours<168?0.85:0.70;return clamp(p*m)}
function scoreFreshness(v:RawVideo){const d=v.ageHours<24?100:v.ageHours<48?90:v.ageHours<72?78:v.ageHours<120?62:v.ageHours<168?48:v.ageHours<240?32:20;return clamp(d+(v.vphNow>v.vphPrev?15:0))}
function scoreReproducibility(v:RawVideo){const b:Record<string,number>={Beauty:92,Fashion:90,Food:95,Education:93,Lifestyle:88,Humor:85,Storytelling:80};const pen=v.creator.followers>1000000?15:v.creator.followers>200000?8:0;return clamp((( b[v.category]??85)-pen)*0.9)}
function scoreSaturation(v:RawVideo){const a=v.ageHours<48?0:v.ageHours<120?20:v.ageHours<240?50:80;const c=Math.min(v.similarCount/50,1)*80;const r=v.creator.followers>1000000?20:v.creator.followers>100000?10:0;return clamp(0.4*a+0.4*c+0.2*r)}
function scoreOpp(vel:number,fresh:number,sat:number,repro:number,eng:number){return clamp(0.25*vel+0.20*fresh+0.20*(100-sat)+0.20*repro+0.15*eng)}
function scoreMaster(opp:number,eng:number,vel:number,reach:number,fresh:number,repro:number,sat:number){let b=0.20*opp+0.20*eng+0.15*vel+0.15*reach+0.10*fresh+0.10*repro+0.10*(100-sat);if(sat>70)b*=0.6;else if(sat>50)b*=0.8;return clamp(b)}
function stage(v:RawVideo,vel:number,sat:number):Stage{if(v.ageHours<48&&vel>70&&sat<25)return 'EMERGING';if(v.ageHours<120&&vel>55&&sat<45)return 'RISING';if(vel>60&&sat<65)return 'HOT';if(vel<25&&v.ageHours>168)return 'DECLINING';if(sat>70||(v.ageHours>240&&vel<30))return 'SATURATED';return 'PEAK'}
function insight(v:RawVideo,st:Stage,s:{vel:number;fresh:number;sat:number;repro:number;eng:number;opp:number}):string{const br=Math.round(v.views/Math.max(v.creator.followers,1));if(st==='SATURATED')return `<span>Too late to adapt.</span> ${v.similarCount} copies exist — saturation is ${Math.round(s.sat)}/100.`;if(st==='EMERGING')return `<span>Breakout from a small creator</span> (${fmt(v.creator.followers)} followers, ${br}× reach). Only ${v.similarCount} copies — window is open.`;if(st==='RISING')return `<span>Gaining momentum fast</span> — ${fmt(v.vphNow)}/hr and ${v.vphNow>v.vphPrev?'accelerating':'holding'}. Only ${v.similarCount} adaptations exist.`;if(st==='HOT')return `<span>Peak virality — act within 48h.</span> Engagement ${Math.round(s.eng)}/100, reproducibility ${Math.round(s.repro)}/100.`;if(st==='DECLINING')return `<span>Fading fast.</span> VPH dropped to ${fmt(v.vphNow)}/hr. Not worth adapting.`;return `<span>Strong signal, timing is tight.</span> Opportunity ${Math.round(s.opp)}/100, saturation ${Math.round(s.sat)}/100.`}
export function scoreVideo(v:RawVideo,maps:PercentileMaps):Scores{const p=vp(v,maps.sorted);const pp=vp(v,maps.vphSorted);const reach=scoreReach(v,p);const eng=scoreEngagement(v);const vel=scoreVelocity(v,pp);const fresh=scoreFreshness(v);const repro=scoreReproducibility(v);const sat=scoreSaturation(v);const opp=scoreOpp(vel,fresh,sat,repro,eng);const trend=scoreMaster(opp,eng,vel,reach,fresh,repro,sat);const st=stage(v,vel,sat);return{reach,eng,vel,fresh,repro,sat,opp,trend,stage:st,insight:insight(v,st,{vel,fresh,sat,repro,eng,opp})}}
export function scoreAll(videos:RawVideo[]):ScoredVideo[]{const maps=buildPercentiles(videos);return videos.map(v=>({...v,scores:scoreVideo(v,maps)}))}
